after_success:
- npm run coverage
before_deploy:
- npm run bundle
before_script:
- npm run typings
cache:
  directories:
  - node_modules
  - typings
language: node_js
node_js:
- '0.12'
- '4'
- '5'
sudo: false
